### ISSUE TITLE
Requirements 1.1.7, 1.1.10 Review

### ISSUE THREAD

**Issue by cnsvr** [bounswe/bounswe2020group3#31]

**Comment by cnsvr** [comment]
I made a few adjustments on Project Page(1.1.10) according to notes at the customer meeting and I will edit scenario 1 and mock-up according to changes on the project page. Can somebody review the project page at any time?

**Comment by cnsvr** [comment]
I also edited the search section and added something. 👍

**Comment by ybedirhanpak** [comment]
### I recommend these changes:

>    * **1.1.7.1.** Users shall be able to search the available content such as events, papers, conferences within the platform if they are looking for something specific.
   * **1.1.7.1.**  Guests and users shall be able to search **events**, projects and other users with search engine.

I added guests since **user** implies registered user and simplified the requirement. 
I added **event** in glossary.

>   * **1.1.7.2.** Users shall be able to utilize the advanced search facility to search for content concerning the research area, topic, scope, and difficulty.

* **1.1.7.2.** Users shall be able to utilize the advanced search facility to customize the search with  filters.

I think 1.2.1.1.2 explains the filter system in details, therefore this requirement should only state that user can use the advanced search facility. We can add additional filters in 1.2.1.1.2 :

> *  **1.2.1.1.2** Advanced search shall support searching with the institution, rating, and skills for the user; project stage, due date and linked event for projects; date, submission deadline, location and type for events.

>    * **1.1.7.3.** Users shall be able to search for a paper or project that is only public, with related keywords.

I think this requirement is not necessary because of this system requirement:

>* **1.2.1.2.1** Search results shall include the public and followed profiles.

>   * **1.1.7.4.** Users shall be able to find related posts with regards to the title, tags, collaborators, type of posts/projects.

I think this should be removed since posts are equal to the projects as stated in customer meeting.

>    * **1.1.7.5** Users shall be able to search for a paper or project with filter criteria such as due date, accessibility, state, type, collaborators.

I think this should be removed since 1.1.7.2 covers advanced search facility and 1.2.1.1.2 explains the filter system.

I recommend to add a sorting requirement:

* Users shall be able to sort search results
  * Users shall be able to sort user-related search results with these criteria: alphabet order, connection with common teammates, rating.
  * Users shall be able to sort project-related search results with these criteria: alphabet order, relation with users' interest.
  * Users shall be able to sort event-related search results with these criteria: alphabet order, date, submission deadline.

**Comment by cnsvr** [comment]
I made some changes upon what you recommend. Thanks 👍

**Comment by cnsvr** [comment]
It's done but according to new feedback of requirements, a new issue will open for same requirement.

**Comment by cnsvr** [comment]
I will review based on the feedback on requirements (20.03.20)

**Comment by cnsvr** [comment]
According to feedback(20.03.20), I followed the steps below:

**Some feedback about this issue are already done March 9, but the first version of requirements sent before that day.**

In 1.1.7 Search,
**(1.1.7.1 — “within the platform if they are looking something specific” should be deleted.)** It's already done at 9 March -> Done 👍  
**(1.1.7.1 and 1.1.7.3/1.1.7.4 intersect — you can embed the information provided in 1.1.7.3 and 1.1.7.4 into 1.1.7.1)** It' already done at 9 March -> Done 👍 
**(You can do the same thing for 1.1.7.2 and 1.1.7.5)** -> It' already done. 👍 

In 1.1.9 Project Page,
**(Project Coordinator and Poster — are they the same thing?)** ->Done 👍  explained in the glossary.
**(Instead of “his/her project’s title or description or type”, you can write it as “the coordinator shall be able to provide the title of the project.)** -> Done 👍 
**(“Linking the project’s GitHub” is not necessary in my opinion.)**  -> Done 👍
