### ISSUE TITLE
Requirements 1.1.1, 1.1.2 Review

### ISSUE THREAD

**Issue by handekarabul** [bounswe/bounswe2020group3#35]

**Comment by ybedirhanpak** [comment]
#### I recommend these changes:
> * **1.1.1.1.** Guests shall be able to register by directing them to the registration page.
* **1.1.1.1.** Guests shall be able to register to the system.
Since how the registration be done is related to the design. Registration itself is enough for this requirement.

> **1.1.1.2.** Guests shall be able to search for  users, papers or projects.
*  **1.1.1.2.** Guests shall be able to search for  users, projects or events.
Since this is clarified in customer meeting.

>   * **1.1.1.4.** Guests shall be able to see public profile pages to get info about other profiles, but not be able to follow, message, comment or rate any registered user.
* **1.1.1.4.** Guests shall be able to see public profile pages.
Since we should only add requirements that users **can** do.

>   * **1.1.1.5.** Guests shall not be able to comment or rate  any paper or project.
>   * **1.1.1.6.** Guests shall not be able to send collaboration request to any paper or project.
* I think these should be removed by the same reason about the change in **1.1.1.4.**

> * **1.1.2.1.**  Users shall provide a unique email address, password, the full name of the user.
* **1.1.2.1.**  Users shall provide a unique email address, a **secure enough password** and full name, while registering.
Since we added **secure enough password** to glossary, we should use it.

>  * **1.1.2.3.**  Users shall be able to sign up with their LinkedIn/Google/Facebook accounts.
* **1.1.2.3.**  Users shall be able to sign up with their Google Scholar / ResearchGate accounts.
Since we clarified this in customer meeting.

> * **1.1.2.5.**  Users shall be able to agree to Terms of Service and Privacy Policy.
* **1.1.2.5.**  Users must to agree to Terms of Service and Privacy Policy while registering
To clarify that this is a must and must be done while registering to the system.

> * **1.1.2.6.**  Users shall be able to retrieve their password to their given e-mail, should they press the button of "forgot your password”.
* **1.1.2.6.**  Users shall be able to retrieve their forgotten password.
The explanation is highly related to design. I think this is enough for the requirement.
