### ISSUE TITLE
1.1.5 will be reviewed

### ISSUE THREAD

**Issue by mhrfky** [bounswe/bounswe2020group3#37]

**Comment by ybedirhanpak** [comment]
## I recommend these changes:
> * **1.1.5.3.** Users shall be able to add ratings and comments to other users' profiles.
* **1.1.5.3.** Users shall be able to add ratings and comments to their current or previous **teammates**.
We decided on customer meeting to that only the people worked together can give rating each other. Otherwise ratings won't give effective results.
Teammates can be added to glossary.

>* **1.1.5.5.** Profiles shall be able to be reported for various reasons given next:Disturbing other users, Sharing unrelated or disturbing posts, Spam, Fake Profile, Stolen Account .
* **1.1.5.5.** Users shall be able to be report other user profiles for these reasons: Disturbing other users, Sharing unrelated or disturbing posts, Spam, Fake Profile, Stolen Account .
This is makes user more active, I think.
