### ISSUE TITLE
[Backend] Creating the Follow System

### ISSUE THREAD

**Issue by liberbey** [bounswe/bounswe2020group3#372]
* **Project:  BACKEND **

* **This is a: FEATURE REQUEST**

* **Description of the issue**

Follow system will be implemented.

**Comment by ybedirhanpak** [comment]
@liberbey I couldn't use the current implementation of the follow mechaninsm. There are two types of follow endpoints:
- follow
- follow_request

I guess I'll use follow_request to send follow requests between users and I'll use follow to display those followers/followings.

It gives internal server error right now, can you look into it?

Also I would like to have these endpoints

- GET /followers?user={userId}
Response is list of user objects, instead of follow objects.

-GET /followings?user={userId}
Response is list of user objects, instead of follow objects.

Thanks

**Comment by liberbey** [comment]
@ybedirhanpak Thanks for the feedbacks. I fixed the bugs and created a new pull request. Regarding to those endpoints, I will create them in next few days -probably until 24.12.2020.

**Comment by ybedirhanpak** [comment]
Current `/users/${id}` endpoint returns these fields. We can remove these fields:
- followings
- followers
- follow_requests

What I'm asking is having these fields in user ( just numeric values of these lists) :
- followings_count
- followers_count
- follow_request_count

We need to fetch those lists with other endpoints.

- followings : Can be fetched with `/follow/` endpoint with query parameter `from_user` but we need to populate user objects in these follow objects. I mean, we get a response like this and `from_user` and `to_user` states ids of the users. We need to get the `"to_user"` to be `User` object instead of id.

```
 {
    "from_user": 21,
    "to_user": 2,
    "created": "2020-12-22T13:06:17.639118Z"
  }
```

- followers: Can also be fetched with `/follow/` endpoint with query parameter `to_user`. We need to get the `"from_user"` to be `User` object instead of id.

Therefore, both `from_user` and `to_user` needs to be populated with related User object.

- follow_requests: For this object, there is no query parameter to filter follow_requests with `to_user`. We both need to add this query parameter and populate the result with User objects.

I know it seems a bit long and complicated process, but I cannot implement follow functionality in android without these changes. It's not the only way to implement it. I can try to come up with a solution if you want, so that both you won't waste your time to understand my needs and I won't wait you to implement it.

**Comment by liberbey** [comment]
Since I changed to Frontend team and there is a merged pull request, I am closing the issue.
